---
name: lint

on:
  workflow_dispatch:
  
  push:
    branches-ignore:
      - master
      - main
  
  pull_request:
    branches-ignore:
      - master
      - main
      
jobs:
  lint:
    name: Lint the code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Lint
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
