---
name: pre

on:
  workflow_run:
    branches:
      - 'main'
      - 'master'
    workflows:
      - lint
    types:
      - completed

jobs:
  pre:
    runs-on: ubuntu-latest
    needs:
      - lint
    outputs:
      version: ${{ steps.get_app_version.outputs.app_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Get application version from Dockerfile
        id: get_app_version
        run: echo "::set-output name=app_version::$(grep 'ARG HYPER_VERSION' Dockerfile | sed -e 's/^.*=//g')"
        shell: bash
