name: release

on:
  workflow_run:
    branches:
      - 'main'
      - 'master'
    workflows:
      - lint
      - pre
      - tag
    type:
      - complete

jobs:

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - pre
      - lint
    steps:

      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to RedHat Container Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          VERSION: ${{ needs.pre.outputs.version }}
          RELEASE: ${{ needs.tag.outputs.tag }}
        with:
          context: .
          load: true
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository_owner }}/hyperglass:latest
            ${{ github.repository_owner }}/hyperglass:${{ env.VERSION }}-${{ env.RELEASE }}
            ghcr.io/${{ github.repository_owner }}/hyperglass:latest
            ghcr.io/${{ github.repository_owner }}/hyperglass:${{ env.VERSION }}-${{ env.RELEASE }}
            quay.io/${{ github.repository_owner }}/hyperglass:latest
            quay.io/${{ github.repository_owner }}/hyperglass:${{ env.VERSION }}-${{ env.RELEASE }}

      - name: Export hyperglass image archive
        run: >
          docker save ${{ github.repository_owner }}/hyperglass:${{ env.VERSION }}-${{ env.RELEASE }} | gzip
          > hyperglass_${{ env.VERSION }}_release_${{ env.RELEASE }}.gzip

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Docker image
          path: |
            hyperglass_${{ env.VERSION }}_release_${{ env.RELEASE }}.gzip

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.tag.outputs.tag }}
          name: Release ${{ needs.tag.outputs.tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
