---
name: pre

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_run:
    workflows:
      - gather
    types:
      - completed
    branches:
      - main
      - master

jobs:
  docker:
    name: Build docker images
    runs-on: ubuntu-latest

    needs:
      - gathering
      - tagging

    env:
      VERSION: ${{ needs.gathering.outputs.version }}
      RELEASE: ${{ needs.tagging.outputs.tag }}

      DOCKERHUB_REGISTRY: docker.io
      GITHUB_REGISTRY: ghcr.io
      REDHAT_REGISTRY: quay.io

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ github.repository_owner }}/hyperglass
            ghcr.io/${{ github.repository_owner }}/hyperglass
            quay.io/${{ github.repository_owner }}/hyperglass
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=${{ env.VERSION }}-{{ version }},value=${{ env.RELEASE }}
            type=semver,pattern=${{ env.VERSION }}-{{ major }}.{{ minor }},value=${{ env.RELEASE }}
            type=semver,pattern=${{ env.VERSION }}-{{ major }},value=${{ env.RELEASE }}
            type=sha
            type=sha,format=long

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKERHUB_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to RedHat Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REDHAT_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Export hyperglass image archive
        run: >
          docker save ${{ github.repository_owner }}/hyperglass:${{ env.VERSION }}-${{ env.RELEASE }} | gzip
          > hyperglass_${{ env.VERSION }}_release_${{ env.RELEASE }}.gzip

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Upload GZIP archive to GitHub artifacts
          path: hyperglass_${{ env.VERSION }}_release_${{ env.RELEASE }}.gzip
