name: docker

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get application version frorm Dockerfile
        run: echo "VERSION=$(grep 'ARG HYPER_VERSION' Dockerfile | sed -e 's/^.*=//g')" >> $GITHUB_ENV
        shell: bash

      - name: Get release verion from GitHub env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            timrabl/hyperglass:latest
            timrabl/hyperglass:${{ env.VERSION }}-${{ env.RELEASE_VERSION }}
            ghcr.io/timrabl/hyperglass:latest
            ghcr.io/timrabl/hyperglass:${{ env.VERSION }}-${{ env.RELEASE_VERSION }}
