name: docker

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
  pull_request:
    tags:
      - 'v*'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.ref, '/tags/v')
    env:
      DOCKER_PATH: .
    steps:
      - name: Get application version frorm Dockerfile
        run: echo ::set-env name=VERSION::$(grep 'ARG HYPER_VERSION' ${DOCKER_PATH}/Dockerfile | sed -e 's/^.*=//g')
        shell: bash

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${DOCKER_PATH}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            timrabl/hyperglass:latest
            timrabl/hyperglass:${{ env.HYPER_VERSION }}-${GITHUB_REF##*/}
            ghcr.io/timrabl/hyperglass:latest
            ghcr.io/timrabl/hyperglass:${{ env.HYPER_VERSION }}-${GITHUB_REF##*/}
